"""init

Revision ID: ae8ab3fc3257
Revises: 8df62091c279
Create Date: 2019-11-27 18:53:50.671902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8ab3fc3257'
down_revision = '8df62091c279'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
