"""use new models Page and User

Revision ID: 8df62091c279
Revises: 5c4e68cfdae1
Create Date: 2019-11-27 18:51:08.677748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df62091c279'
down_revision = '5c4e68cfdae1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
